# coding: utf-8

# flake8: noqa
"""
    OFIQ API

    API for perfoming requests against the Open Face Image Quality service.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from ofiq_client.models.analysis_request_data import AnalysisRequestData
from ofiq_client.models.analysis_response_data import AnalysisResponseData
from ofiq_client.models.bounding_box import BoundingBox
from ofiq_client.models.face_image_analysis_result import FaceImageAnalysisResult
from ofiq_client.models.image import Image
from ofiq_client.models.landmarks import Landmarks
from ofiq_client.models.point import Point
from ofiq_client.models.quality_assessment_result import QualityAssessmentResult
from ofiq_client.models.quality_assessment_results import QualityAssessmentResults
from ofiq_client.models.scalar_quality_analysis_result import ScalarQualityAnalysisResult
from ofiq_client.models.scalar_quality_response_data import ScalarQualityResponseData
from ofiq_client.models.vector_quality_analysis_result import VectorQualityAnalysisResult
from ofiq_client.models.vector_quality_response_data import VectorQualityResponseData
