# coding: utf-8

"""
    OFIQ API

    API for perfoming requests against the Open Face Image Quality service.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Image(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'base64_data': 'str'
    }

    attribute_map = {
        'base64_data': 'base64_data'
    }

    def __init__(self, base64_data=None):  # noqa: E501
        """Image - a model defined in Swagger"""  # noqa: E501
        self._base64_data = None
        self.discriminator = None
        self.base64_data = base64_data

    @property
    def base64_data(self):
        """Gets the base64_data of this Image.  # noqa: E501

        Base64 encoded representation of the image data.  # noqa: E501

        :return: The base64_data of this Image.  # noqa: E501
        :rtype: str
        """
        return self._base64_data

    @base64_data.setter
    def base64_data(self, base64_data):
        """Sets the base64_data of this Image.

        Base64 encoded representation of the image data.  # noqa: E501

        :param base64_data: The base64_data of this Image.  # noqa: E501
        :type: str
        """
        if base64_data is None:
            raise ValueError("Invalid value for `base64_data`, must not be `None`")  # noqa: E501

        self._base64_data = base64_data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Image, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Image):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
