# coding: utf-8

"""
    OFIQ API

    API for perfoming requests against the Open Face Image Quality service.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ScalarQualityResponseData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error': 'str',
        'results': 'ScalarQualityAnalysisResult'
    }

    attribute_map = {
        'error': 'error',
        'results': 'results'
    }

    def __init__(self, error=None, results=None):  # noqa: E501
        """ScalarQualityResponseData - a model defined in Swagger"""  # noqa: E501
        self._error = None
        self._results = None
        self.discriminator = None
        if error is not None:
            self.error = error
        self.results = results

    @property
    def error(self):
        """Gets the error of this ScalarQualityResponseData.  # noqa: E501

        A string containing an error desciption if any error occured. A value 'ok' means no errors occured.  # noqa: E501

        :return: The error of this ScalarQualityResponseData.  # noqa: E501
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this ScalarQualityResponseData.

        A string containing an error desciption if any error occured. A value 'ok' means no errors occured.  # noqa: E501

        :param error: The error of this ScalarQualityResponseData.  # noqa: E501
        :type: str
        """

        self._error = error

    @property
    def results(self):
        """Gets the results of this ScalarQualityResponseData.  # noqa: E501


        :return: The results of this ScalarQualityResponseData.  # noqa: E501
        :rtype: ScalarQualityAnalysisResult
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this ScalarQualityResponseData.


        :param results: The results of this ScalarQualityResponseData.  # noqa: E501
        :type: ScalarQualityAnalysisResult
        """
        if results is None:
            raise ValueError("Invalid value for `results`, must not be `None`")  # noqa: E501

        self._results = results

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ScalarQualityResponseData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScalarQualityResponseData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
