# coding: utf-8

from __future__ import absolute_import

from typing import Optional

from ofiq_server.models.base_model_ import Model
from ofiq_server.models.image import Image  # noqa: F401,E501
from ofiq_server import util


class AnalysisRequestData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, image: Optional[Image]=None):  # noqa: E501
        """AnalysisRequestData - a model defined in Swagger

        :param image: The image of this AnalysisRequestData.  # noqa: E501
        :type image: Image
        """
        self.swagger_types = {
            'image': Image
        }

        self.attribute_map = {
            'image': 'image'
        }
        self._image = image

    @classmethod
    def from_dict(cls, dikt) -> 'AnalysisRequestData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AnalysisRequestData of this AnalysisRequestData.  # noqa: E501
        :rtype: AnalysisRequestData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image(self) -> Optional[Image]:
        """Gets the image of this AnalysisRequestData.


        :return: The image of this AnalysisRequestData.
        :rtype: Image
        """
        return self._image

    @image.setter
    def image(self, image: Image):
        """Sets the image of this AnalysisRequestData.


        :param image: The image of this AnalysisRequestData.
        :type image: Image
        """
        if image is None:
            raise ValueError("Invalid value for `image`, must not be `None`")  # noqa: E501

        self._image = image
