# coding: utf-8

from __future__ import absolute_import

from typing import Optional

from ofiq_server.models.base_model_ import Model
from ofiq_server.models.face_image_analysis_result import FaceImageAnalysisResult  # noqa: F401,E501
from ofiq_server import util


class AnalysisResponseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error: Optional[str]=None,
                 results: Optional[FaceImageAnalysisResult]=None):  # noqa: E501
        """AnalysisResponseData - a model defined in Swagger

        :param error: The error of this AnalysisResponseData.  # noqa: E501
        :type error: str
        :param results: The results of this AnalysisResponseData.  # noqa: E501
        :type results: FaceImageAnalysisResult
        """
        self.swagger_types = {
            'error': str,
            'results': FaceImageAnalysisResult
        }

        self.attribute_map = {
            'error': 'error',
            'results': 'results'
        }
        self._error = error
        self._results = results

    @classmethod
    def from_dict(cls, dikt) -> 'AnalysisResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AnalysisResponseData of this AnalysisResponseData.  # noqa: E501
        :rtype: AnalysisResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> Optional[str]:
        """Gets the error of this AnalysisResponseData.

        A string containing an error desciption if any error occured. A value 'ok' means no errors occured.  # noqa: E501

        :return: The error of this AnalysisResponseData.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this AnalysisResponseData.

        A string containing an error desciption if any error occured. A value 'ok' means no errors occured.  # noqa: E501

        :param error: The error of this AnalysisResponseData.
        :type error: str
        """

        self._error = error

    @property
    def results(self) -> Optional[FaceImageAnalysisResult]:
        """Gets the results of this AnalysisResponseData.


        :return: The results of this AnalysisResponseData.
        :rtype: FaceImageAnalysisResult
        """
        return self._results

    @results.setter
    def results(self, results: FaceImageAnalysisResult):
        """Sets the results of this AnalysisResponseData.


        :param results: The results of this AnalysisResponseData.
        :type results: FaceImageAnalysisResult
        """
        if results is None:
            raise ValueError("Invalid value for `results`, must not be `None`")  # noqa: E501

        self._results = results
