# coding: utf-8

from __future__ import absolute_import

from typing import Optional

from ofiq_server.models.base_model_ import Model
from ofiq_server import util


class BoundingBox(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self,
                 x: Optional[int]=None,
                 y: Optional[int]=None,
                 width: Optional[int]=None,
                 height: Optional[int]=None):  # noqa: E501
        """BoundingBox - a model defined in Swagger

        :param x: The x of this BoundingBox.  # noqa: E501
        :type x: int
        :param y: The y of this BoundingBox.  # noqa: E501
        :type y: int
        :param width: The width of this BoundingBox.  # noqa: E501
        :type width: int
        :param height: The height of this BoundingBox.  # noqa: E501
        :type height: int
        """
        self.swagger_types = {
            'x': int,
            'y': int,
            'width': int,
            'height': int
        }

        self.attribute_map = {
            'x': 'x',
            'y': 'y',
            'width': 'width',
            'height': 'height'
        }
        self._x = x
        self._y = y
        self._width = width
        self._height = height

    @classmethod
    def from_dict(cls, dikt) -> 'BoundingBox':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BoundingBox of this BoundingBox.  # noqa: E501
        :rtype: BoundingBox
        """
        return util.deserialize_model(dikt, cls)

    @property
    def x(self) -> Optional[int]:
        """Gets the x of this BoundingBox.

        x-coordinate of the top left corner of the face region in the image  # noqa: E501

        :return: The x of this BoundingBox.
        :rtype: int
        """
        return self._x

    @x.setter
    def x(self, x: int):
        """Sets the x of this BoundingBox.

        x-coordinate of the top left corner of the face region in the image  # noqa: E501

        :param x: The x of this BoundingBox.
        :type x: int
        """
        if x is None:
            raise ValueError("Invalid value for `x`, must not be `None`")  # noqa: E501

        self._x = x

    @property
    def y(self) -> Optional[int]:
        """Gets the y of this BoundingBox.

        y-coordinate of the top left corner of the face region in the image  # noqa: E501

        :return: The y of this BoundingBox.
        :rtype: int
        """
        return self._y

    @y.setter
    def y(self, y: int):
        """Sets the y of this BoundingBox.

        y-coordinate of the top left corner of the face region in the image  # noqa: E501

        :param y: The y of this BoundingBox.
        :type y: int
        """
        if y is None:
            raise ValueError("Invalid value for `y`, must not be `None`")  # noqa: E501

        self._y = y

    @property
    def width(self) -> Optional[int]:
        """Gets the width of this BoundingBox.

        Width of the face region in the image  # noqa: E501

        :return: The width of this BoundingBox.
        :rtype: int
        """
        return self._width

    @width.setter
    def width(self, width: int):
        """Sets the width of this BoundingBox.

        Width of the face region in the image  # noqa: E501

        :param width: The width of this BoundingBox.
        :type width: int
        """
        if width is None:
            raise ValueError("Invalid value for `width`, must not be `None`")  # noqa: E501

        self._width = width

    @property
    def height(self) -> Optional[int]:
        """Gets the height of this BoundingBox.

        Height of the face region in the image  # noqa: E501

        :return: The height of this BoundingBox.
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height: int):
        """Sets the height of this BoundingBox.

        Height of the face region in the image  # noqa: E501

        :param height: The height of this BoundingBox.
        :type height: int
        """
        if height is None:
            raise ValueError("Invalid value for `height`, must not be `None`")  # noqa: E501

        self._height = height
