# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import Optional

from ofiq_server.models.base_model_ import Model
from ofiq_server import util


class Image(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, base64_data: Optional[bytearray]=None):  # noqa: E501
        """Image - a model defined in Swagger

        :param base64_data: The base64_data of this Image.  # noqa: E501
        :type base64_data: bytearray
        """
        self.swagger_types = {
            'base64_data': bytearray
        }

        self.attribute_map = {
            'base64_data': 'base64_data'
        }
        self._base64_data = base64_data

    @classmethod
    def from_dict(cls, dikt) -> 'Image':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Image of this Image.  # noqa: E501
        :rtype: Image
        """
        return util.deserialize_model(dikt, cls)

    @property
    def base64_data(self) -> Optional[bytearray]:
        """Gets the base64_data of this Image.

        Base64 encoded representation of the image data.  # noqa: E501

        :return: The base64_data of this Image.
        :rtype: bytearray
        """
        return self._base64_data

    @base64_data.setter
    def base64_data(self, base64_data: bytearray):
        """Sets the base64_data of this Image.

        Base64 encoded representation of the image data.  # noqa: E501

        :param base64_data: The base64_data of this Image.
        :type base64_data: bytearray
        """
        if base64_data is None:
            raise ValueError("Invalid value for `base64_data`, must not be `None`")  # noqa: E501

        self._base64_data = base64_data
