# coding: utf-8

from __future__ import absolute_import

from typing import Optional, List

from ofiq_server.models.base_model_ import Model
from ofiq_server.models.point import Point  # noqa: F401,E501
from ofiq_server import util


class Landmarks(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, points: Optional[List[Point]]=None):  # noqa: E501
        """Landmarks - a model defined in Swagger

        :param points: The points of this Landmarks.  # noqa: E501
        :type points: List[Point]
        """
        self.swagger_types = {
            'points': List[Point]
        }

        self.attribute_map = {
            'points': 'points'
        }
        self._points = points

    @classmethod
    def from_dict(cls, dikt) -> 'Landmarks':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Landmarks of this Landmarks.  # noqa: E501
        :rtype: Landmarks
        """
        return util.deserialize_model(dikt, cls)

    @property
    def points(self) -> Optional[List[Point]]:
        """Gets the points of this Landmarks.


        :return: The points of this Landmarks.
        :rtype: List[Point]
        """
        return self._points

    @points.setter
    def points(self, points: List[Point]):
        """Sets the points of this Landmarks.


        :param points: The points of this Landmarks.
        :type points: List[Point]
        """
        if points is None:
            raise ValueError("Invalid value for `points`, must not be `None`")  # noqa: E501

        self._points = points
