# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import Optional

from ofiq_server.models.base_model_ import Model
from ofiq_server import util


class Point(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, x: Optional[int]=None, y: Optional[int]=None):  # noqa: E501
        """Point - a model defined in Swagger

        :param x: The x of this Point.  # noqa: E501
        :type x: int
        :param y: The y of this Point.  # noqa: E501
        :type y: int
        """
        self.swagger_types = {
            'x': int,
            'y': int
        }

        self.attribute_map = {
            'x': 'x',
            'y': 'y'
        }
        self._x = x
        self._y = y

    @classmethod
    def from_dict(cls, dikt) -> 'Point':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Point of this Point.  # noqa: E501
        :rtype: Point
        """
        return util.deserialize_model(dikt, cls)

    @property
    def x(self) -> Optional[int]:
        """Gets the x of this Point.

        x-coordinate of the point  # noqa: E501

        :return: The x of this Point.
        :rtype: int
        """
        return self._x

    @x.setter
    def x(self, x: int):
        """Sets the x of this Point.

        x-coordinate of the point  # noqa: E501

        :param x: The x of this Point.
        :type x: int
        """
        if x is None:
            raise ValueError("Invalid value for `x`, must not be `None`")  # noqa: E501

        self._x = x

    @property
    def y(self) -> Optional[int]:
        """Gets the y of this Point.

        y-coordinate of the point  # noqa: E501

        :return: The y of this Point.
        :rtype: int
        """
        return self._y

    @y.setter
    def y(self, y: int):
        """Sets the y of this Point.

        y-coordinate of the point  # noqa: E501

        :param y: The y of this Point.
        :type y: int
        """
        if y is None:
            raise ValueError("Invalid value for `y`, must not be `None`")  # noqa: E501

        self._y = y
