# coding: utf-8

from __future__ import absolute_import

from typing import Optional

from ofiq_server.models.base_model_ import Model
from ofiq_server.models.scalar_quality_analysis_result import ScalarQualityAnalysisResult  # noqa: F401,E501
from ofiq_server import util


class ScalarQualityResponseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self,
                 error: Optional[str]=None,
                 results: Optional[ScalarQualityAnalysisResult]=None):  # noqa: E501
        """ScalarQualityResponseData - a model defined in Swagger

        :param error: The error of this ScalarQualityResponseData.  # noqa: E501
        :type error: str
        :param results: The results of this ScalarQualityResponseData.  # noqa: E501
        :type results: ScalarQualityAnalysisResult
        """
        self.swagger_types = {
            'error': str,
            'results': ScalarQualityAnalysisResult
        }

        self.attribute_map = {
            'error': 'error',
            'results': 'results'
        }
        self._error = error
        self._results = results

    @classmethod
    def from_dict(cls, dikt) -> 'ScalarQualityResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ScalarQualityResponseData of this ScalarQualityResponseData.  # noqa: E501
        :rtype: ScalarQualityResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> Optional[str]:
        """Gets the error of this ScalarQualityResponseData.

        A string containing an error desciption if any error occured. A value 'ok' means no errors occured.  # noqa: E501

        :return: The error of this ScalarQualityResponseData.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this ScalarQualityResponseData.

        A string containing an error desciption if any error occured. A value 'ok' means no errors occured.  # noqa: E501

        :param error: The error of this ScalarQualityResponseData.
        :type error: str
        """

        self._error = error

    @property
    def results(self) -> Optional[ScalarQualityAnalysisResult]:
        """Gets the results of this ScalarQualityResponseData.


        :return: The results of this ScalarQualityResponseData.
        :rtype: ScalarQualityAnalysisResult
        """
        return self._results

    @results.setter
    def results(self, results: ScalarQualityAnalysisResult):
        """Sets the results of this ScalarQualityResponseData.


        :param results: The results of this ScalarQualityResponseData.
        :type results: ScalarQualityAnalysisResult
        """
        if results is None:
            raise ValueError("Invalid value for `results`, must not be `None`")  # noqa: E501

        self._results = results
