# coding: utf-8

from __future__ import absolute_import

from typing import Optional

from ofiq_server.models.base_model_ import Model
from ofiq_server.models.vector_quality_analysis_result import VectorQualityAnalysisResult  # noqa: F401,E501
from ofiq_server import util


class VectorQualityResponseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self,
                 error: Optional[str]=None,
                 results: Optional[VectorQualityAnalysisResult]=None):  # noqa: E501
        """VectorQualityResponseData - a model defined in Swagger

        :param error: The error of this VectorQualityResponseData.  # noqa: E501
        :type error: str
        :param results: The results of this VectorQualityResponseData.  # noqa: E501
        :type results: VectorQualityAnalysisResult
        """
        self.swagger_types = {
            'error': str,
            'results': VectorQualityAnalysisResult
        }

        self.attribute_map = {
            'error': 'error',
            'results': 'results'
        }
        self._error = error
        self._results = results

    @classmethod
    def from_dict(cls, dikt) -> 'VectorQualityResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VectorQualityResponseData of this VectorQualityResponseData.  # noqa: E501
        :rtype: VectorQualityResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> Optional[str]:
        """Gets the error of this VectorQualityResponseData.

        A string containing an error desciption if any error occured. A value 'ok' means no errors occured.  # noqa: E501

        :return: The error of this VectorQualityResponseData.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this VectorQualityResponseData.

        A string containing an error desciption if any error occured. A value 'ok' means no errors occured.  # noqa: E501

        :param error: The error of this VectorQualityResponseData.
        :type error: str
        """

        self._error = error

    @property
    def results(self) -> Optional[VectorQualityAnalysisResult]:
        """Gets the results of this VectorQualityResponseData.


        :return: The results of this VectorQualityResponseData.
        :rtype: VectorQualityAnalysisResult
        """
        return self._results

    @results.setter
    def results(self, results: VectorQualityAnalysisResult):
        """Sets the results of this VectorQualityResponseData.


        :param results: The results of this VectorQualityResponseData.
        :type results: VectorQualityAnalysisResult
        """
        if results is None:
            raise ValueError("Invalid value for `results`, must not be `None`")  # noqa: E501

        self._results = results
