list(APPEND PUBLIC_HEADER_LIST 
	${OFIQLIB_SOURCE_DIR}/include/ofiq_lib.h
	${OFIQLIB_SOURCE_DIR}/include/ofiq_structs.h
)

list(APPEND libImplementationSources 
	${OFIQLIB_SOURCE_DIR}/src/OFIQImpl.cpp
	${OFIQLIB_SOURCE_DIR}/src/OFIQInitialization.cpp
)

list(APPEND module_sources 
	${libImplementationSources}
	${OFIQLIB_SOURCE_DIR}/modules/detectors/src/detectors.cpp
	${OFIQLIB_SOURCE_DIR}/modules/detectors/src/opencv_ssd_face_detector.cpp
	${OFIQLIB_SOURCE_DIR}/modules/landmarks/src/adnet_landmarks.cpp
	${OFIQLIB_SOURCE_DIR}/modules/landmarks/src/FaceMeasures.cpp
	${OFIQLIB_SOURCE_DIR}/modules/landmarks/src/landmarks.cpp
	${OFIQLIB_SOURCE_DIR}/modules/landmarks/src/PartExtractor.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/BackgroundUniformity.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/CompressionArtifacts.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/DynamicRange.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/Executor.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/ExpressionNeutrality.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/EyesOpen.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/EyesVisible.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/FaceOcclusionPrevention.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/CropOfTheFaceImage.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/UnifiedQualityScore.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/IlluminationUniformity.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/InterEyeDistance.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/Luminance.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/Measure.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/MeasureFactory.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/MouthOcclusionPrevention.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/MouthClosed.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/NoHeadCoverings.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/OverExposurePrevention.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/UnderExposurePrevention.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/HeadSize.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/HeadPose.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/Sharpness.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/SingleFacePresent.cpp
	${OFIQLIB_SOURCE_DIR}/modules/measures/src/NaturalColour.cpp
	${OFIQLIB_SOURCE_DIR}/modules/poseEstimators/src/HeadPose3DDFAV2.cpp
	${OFIQLIB_SOURCE_DIR}/modules/poseEstimators/src/poseEstimators.cpp
	${OFIQLIB_SOURCE_DIR}/modules/segmentations/src/ONNXRTSegmentation.cpp
	${OFIQLIB_SOURCE_DIR}/modules/segmentations/src/FaceParsing.cpp
	${OFIQLIB_SOURCE_DIR}/modules/segmentations/src/FaceOcclusionSegmentation.cpp
	${OFIQLIB_SOURCE_DIR}/modules/segmentations/src/segmentations.cpp
	${OFIQLIB_SOURCE_DIR}/modules/utils/src/Configuration.cpp
	${OFIQLIB_SOURCE_DIR}/modules/utils/src/OFIQError.cpp
	${OFIQLIB_SOURCE_DIR}/modules/utils/src/image_io.cpp
	${OFIQLIB_SOURCE_DIR}/modules/utils/src/image_utils.cpp
	${OFIQLIB_SOURCE_DIR}/modules/utils/src/Session.cpp
	${OFIQLIB_SOURCE_DIR}/modules/utils/src/utils.cpp
)

list(APPEND module_headers
	${PUBLIC_HEADER_LIST}
	${OFIQLIB_SOURCE_DIR}/include/ofiq_lib_impl.h
	${OFIQLIB_SOURCE_DIR}/modules/detectors/AllDetectors.h
	${OFIQLIB_SOURCE_DIR}/modules/detectors/detectors.h
	${OFIQLIB_SOURCE_DIR}/modules/detectors/opencv_ssd_face_detector.h
	${OFIQLIB_SOURCE_DIR}/modules/landmarks/AllLandmarks.h
	${OFIQLIB_SOURCE_DIR}/modules/landmarks/adnet_landmarks.h
	${OFIQLIB_SOURCE_DIR}/modules/landmarks/adnet_FaceMap.h
	${OFIQLIB_SOURCE_DIR}/modules/landmarks/FaceMeasures.h
	${OFIQLIB_SOURCE_DIR}/modules/landmarks/FaceParts.h
	${OFIQLIB_SOURCE_DIR}/modules/landmarks/landmarks.h
	${OFIQLIB_SOURCE_DIR}/modules/landmarks/PartExtractor.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/AllMeasures.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/BackgroundUniformity.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/CompressionArtifacts.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/DynamicRange.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/Executor.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/ExpressionNeutrality.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/EyesOpen.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/EyesVisible.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/FaceOcclusionPrevention.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/CropOfTheFaceImage.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/UnifiedQualityScore.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/IlluminationUniformity.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/InterEyeDistance.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/Luminance.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/Measure.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/MeasureFactory.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/MouthOcclusionPrevention.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/MouthClosed.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/NoHeadCoverings.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/OverExposurePrevention.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/UnderExposurePrevention.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/HeadSize.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/HeadPose.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/Sharpness.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/SingleFacePresent.h
	${OFIQLIB_SOURCE_DIR}/modules/measures/NaturalColour.h
	${OFIQLIB_SOURCE_DIR}/modules/poseEstimators/AllPoseEstimators.h
	${OFIQLIB_SOURCE_DIR}/modules/poseEstimators/HeadPose3DDFAV2.h
	${OFIQLIB_SOURCE_DIR}/modules/poseEstimators/poseEstimators.h
	${OFIQLIB_SOURCE_DIR}/modules/segmentations/ONNXRTSegmentation.h
	${OFIQLIB_SOURCE_DIR}/modules/segmentations/FaceParsing.h
	${OFIQLIB_SOURCE_DIR}/modules/segmentations/FaceOcclusionSegmentation.h
	${OFIQLIB_SOURCE_DIR}/modules/segmentations/segmentations.h
	${OFIQLIB_SOURCE_DIR}/modules/utils/Configuration.h
	${OFIQLIB_SOURCE_DIR}/modules/utils/OFIQError.h
	${OFIQLIB_SOURCE_DIR}/modules/utils/image_io.h
	${OFIQLIB_SOURCE_DIR}/modules/utils/image_utils.h
	${OFIQLIB_SOURCE_DIR}/modules/utils/NeuronalNetworkContainer.h
	${OFIQLIB_SOURCE_DIR}/modules/utils/Session.h
	${OFIQLIB_SOURCE_DIR}/modules/utils/utils.h
)